### ISSUE TITLE
out-of-date data of GDSC?

### ISSUE THREAD

**Issue by zhaoliang0302** [paulgeeleher/pRRophetic2#1]
Hi,
I found only 138 kinds of drugs in pRRopheticPredict function but the GDSC official wbesite has more than 200 drugs, I can't perform ananlysis on my research target drugs, such as Temozolomide. Can you update your package with newest data?
Much thanks

**Comment by paulgeeleher** [comment]
Hi zhaoliang0302

You need to use the flag dataset="cgp2016" in the pRRopeticPredict() function in order to use the updated (2016 Cell paper) release of the GDSC data.

**Comment by zhaoliang0302** [comment]
Can you update the data to the newest version cgp2019? My target drug is not in the cgp2016 but in 2019. Or can you tell me how to add new drug data into this package if you have no spare time to do? I really want to use pRRopeticPredict() function.
Thanks

**Comment by zhaoliang0302** [comment]
Hi,
Can you reply to me if you have spare time?

**Comment by paulgeeleher** [comment]
Dear Sir,

Your drug, Temozolomide, is in the "cgp2016" group.

Best wishes

**Comment by zhaoliang0302** [comment]
Thanks a lot, I have solved this problem. I feel sorry if I bothered you：-）
